import { Product } from "@/products/interfaces/product.interfaces";

interface SeedData {
  products: Product[];
}

export const initialData: SeedData = {
  products: [
    {
      name: "Camaron",
      id: "1",
      description: "Crustáceo de cuerpo largo y delgado",
      stockInPounds: "15",
      pricePerPound: "10.99",
      imgUrl: "langostino.jpeg",
    },
    {
      name: "Pulpo",
      id: "2",
      description: "Molusco de cuerpo blando y tentáculos",
      stockInPounds: "8",
      pricePerPound: "15.99",
      imgUrl: "gamba.jpeg",
    },
    {
      name: "Calamar",
      id: "3",
      description: "Molusco de cuerpo alargado y tentáculos",
      stockInPounds: "12",
      pricePerPound: "8.99",
      imgUrl: "calamar.jpeg",
    },
    {
      name: "Langosta",
      id: "4",
      description: "Crustáceo de cuerpo robusto y pinzas",
      stockInPounds: "5",
      pricePerPound: "25.99",
      imgUrl: "langosta.jpeg",
    },
    {
      name: "Cangrejo",
      id: "5",
      description: "Crustáceo de cuerpo ancho y patas",
      stockInPounds: "7",
      pricePerPound: "12.99",
      imgUrl: "cangrejo.jpeg",
    },
    {
      name: "Mejillón",
      id: "6",
      description: "Molusco de concha negra y forma ovalada",
      stockInPounds: "10",
      pricePerPound: "6.99",
      imgUrl: "mejillon.jpeg",
    },
    {
      name: "Ostra",
      id: "7",
      description: "Molusco de concha rugosa y forma redonda",
      stockInPounds: "4",
      pricePerPound: "9.99",
      imgUrl: "ostra.jpeg",
    },
    {
      name: "Almeja",
      id: "8",
      description: "Molusco de concha blanca y forma ovalada",
      stockInPounds: "6",
      pricePerPound: "7.99",
      imgUrl: "almeja.jpeg",
    },
    {
      name: "Pez Espada",
      id: "9",
      description: "Pez de cuerpo largo y afilado",
      stockInPounds: "3",
      pricePerPound: "18.99",
      imgUrl: "pez-espada.jpeg",
    },
    {
      name: "Atún",
      id: "10",
      description: "Pez de cuerpo grande y aletas",
      stockInPounds: "2",
      pricePerPound: "20.99",
      imgUrl: "atun.jpeg",
    },
    {
      name: "Salmón",
      id: "11",
      description: "Pez de cuerpo plateado y escamas",
      stockInPounds: "4",
      pricePerPound: "16.99",
      imgUrl: "salmon.jpeg",
    },
    {
      name: "Bacalao",
      id: "12",
      description: "Pez de cuerpo alargado y mandíbula prominente",
      stockInPounds: "5",
      pricePerPound: "14.99",
      imgUrl: "bacalao.jpeg",
    },
    {
      name: "Merluza",
      id: "13",
      description: "Pez de cuerpo blanco y ojos grandes",
      stockInPounds: "6",
      pricePerPound: "13.99",
      imgUrl: "merluza.jpeg",
    },
    {
      name: "Cabracho",
      id: "14",
      description: "Pez de cuerpo rojo y cabeza prominente",
      stockInPounds: "7",
      pricePerPound: "11.99",
      imgUrl: "cabracho.jpeg",
    },
    {
      name: "Rape",
      id: "15",
      description: "Pez de cuerpo aplanado y boca grande",
      stockInPounds: "8",
      pricePerPound: "10.99",
      imgUrl: "rape.jpeg",
    },
    {
      name: "Gamba",
      id: "16",
      description: "Crustáceo de cuerpo corto y antenas largas",
      stockInPounds: "9",
      pricePerPound: "9.99",
      imgUrl: "gamba.jpeg",
    },
    {
      name: "Langostino",
      id: "17",
      description: "Crustáceo de cuerpo pequeño y patas largas",
      stockInPounds: "10",
      pricePerPound: "8.99",
      imgUrl: "langostino.jpeg",
    },
    {
      name: "Centollo",
      id: "18",
      description: "Crustáceo de cuerpo redondo y espinas",
      stockInPounds: "11",
      pricePerPound: "7.99",
      imgUrl: "centollo.jpeg",
    },
    {
      name: "Nécora",
      id: "19",
      description: "Crustáceo de cuerpo pequeño y caparazón",
      stockInPounds: "12",
      pricePerPound: "6.99",
      imgUrl: "necora.jpeg",
    },
    {
      name: "Berberecho",
      id: "20",
      description: "Molusco de concha pequeña y forma redonda",
      stockInPounds: "13",
      pricePerPound: "5.99",
      imgUrl: "berberecho.jpeg",
    },
    {
      name: "Caracol de Mar",
      id: "23",
      description: "Molusco de concha en espiral y cuerpo blando",
      stockInPounds: "16",
      pricePerPound: "2.99",
      imgUrl: "caracol-mar.jpeg",
    },
    {
      name: "Caracol de Río",
      id: "24",
      description: "Molusco de concha en espiral y cuerpo blando",
      stockInPounds: "17",
      pricePerPound: "1.99",
      imgUrl: "caracol-rio.jpeg",
    },
  ],
};
